package com.omiinqa.database.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Immutable (Lombok-generated) data record representing one row from the
 * {@code audit_log} table.
 *
 * <p><b>Design pattern — Data Transfer Object (DTO):</b>
 * {@code AuditRecord} is a pure value carrier used by
 * {@link com.omiinqa.database.repositories.AuditRepository} and test
 * assertions. Keeping it behaviour-free ensures the test layer can inspect
 * audit entries without inadvertently triggering application side-effects.</p>
 *
 * <p><b>Audit-log rationale:</b>
 * An audit log captures a tamper-evident trail of who did what to which entity
 * and when. This record reflects the minimal five-column schema commonly
 * mandated by compliance frameworks (SOC-2, HIPAA audit controls, etc.):
 * entity type, action performed, the actor (user or system identity), and
 * timestamp. Tests that verify audit-log correctness assert both that an entry
 * exists and that its fields have the expected values — this DTO makes those
 * assertions readable and type-safe.</p>
 *
 * <p><b>Schema assumption</b> (table: {@code audit_log}):</p>
 * <pre>
 *   id      BIGINT PRIMARY KEY AUTO_INCREMENT / SERIAL
 *   entity  VARCHAR(100) NOT NULL   -- e.g. 'order', 'user', 'product'
 *   action  VARCHAR(50)  NOT NULL   -- e.g. 'CREATE', 'UPDATE', 'DELETE'
 *   actor   VARCHAR(255) NOT NULL   -- email, username, or system identifier
 *   at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 * </pre>
 *
 * <p><b>Lombok annotations used:</b></p>
 * <ul>
 *   <li>{@code @Data} — getters, setters, {@code equals}, {@code hashCode},
 *       {@code toString}.</li>
 *   <li>{@code @Builder} — fluent construction:
 *       {@code AuditRecord.builder().entity("order").action("CREATE").actor("alice").build()}.</li>
 *   <li>{@code @NoArgsConstructor}/{@code @AllArgsConstructor} — required by
 *       {@code @Builder} when combined with {@code @Data}.</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuditRecord {

    /** Surrogate primary key — auto-generated by the database. */
    private Long id;

    /**
     * The entity type that was affected by the audited action.
     * Examples: {@code "order"}, {@code "user"}, {@code "product"}.
     */
    private String entity;

    /**
     * The action performed on the entity.
     * Standard values: {@code "CREATE"}, {@code "UPDATE"}, {@code "DELETE"},
     * {@code "READ"} (used only for sensitive data access logging).
     */
    private String action;

    /**
     * The identity of the actor who performed the action.
     * This may be a user's email address, a service account name, or a
     * system identifier such as {@code "scheduler"}.
     */
    private String actor;

    /**
     * The timestamp at which the audited event occurred.
     * Stored as {@link Object} to accommodate vendor-specific JDBC types
     * ({@code java.sql.Timestamp} for both PostgreSQL and MySQL).
     */
    private Object at;
}
