package com.omiinqa.database.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Immutable (Lombok-generated) data record representing one row from the
 * {@code orders} table.
 *
 * <p><b>Design pattern — Data Transfer Object (DTO):</b>
 * {@code OrderRecord} is the read-side projection used by
 * {@link com.omiinqa.database.repositories.OrderRepository} and test
 * assertions. It is a pure value object with no business logic, making it
 * trivially serialisable, printable, and safe to compare in AssertJ assertions
 * without risk of side-effects.</p>
 *
 * <p><b>Monetary precision:</b> The {@code total} column is mapped to
 * {@link BigDecimal} (fetched via {@code ResultSet.getBigDecimal}) rather than
 * {@code double} to prevent IEEE-754 rounding errors that cause spurious
 * assertion failures when comparing order totals — a well-known pitfall in
 * financial database tests.</p>
 *
 * <p><b>Schema assumption</b> (table: {@code orders}):</p>
 * <pre>
 *   id          BIGINT PRIMARY KEY AUTO_INCREMENT / SERIAL
 *   user_id     BIGINT NOT NULL REFERENCES users(id)
 *   product_id  BIGINT NOT NULL REFERENCES products(id)
 *   quantity    INT NOT NULL CHECK (quantity {@literal >} 0)
 *   total       NUMERIC(12,2) NOT NULL
 *   status      VARCHAR(50) NOT NULL DEFAULT 'pending'
 *   created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 * </pre>
 *
 * <p><b>Lombok annotations used:</b></p>
 * <ul>
 *   <li>{@code @Data} — generates getters, setters, {@code equals}, {@code hashCode},
 *       {@code toString}.</li>
 *   <li>{@code @Builder} — enables fluent construction:
 *       {@code OrderRecord.builder().id(1L).status("shipped").build()}.</li>
 *   <li>{@code @NoArgsConstructor}/{@code @AllArgsConstructor} — required by
 *       {@code @Builder} when combined with {@code @Data}.</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderRecord {

    /** Surrogate primary key — auto-generated by the database. */
    private Long id;

    /**
     * Foreign key referencing {@code users.id}.
     * Identifies the customer who placed this order.
     */
    private Long userId;

    /**
     * Foreign key referencing {@code products.id}.
     * Identifies the product being ordered.
     */
    private Long productId;

    /**
     * Number of product units in this order line.
     * Must be positive; enforced by a {@code CHECK} constraint in the schema.
     */
    private Integer quantity;

    /**
     * Total monetary value of the order ({@code quantity × unit_price}).
     * {@link BigDecimal} avoids IEEE-754 floating-point precision issues when
     * comparing totals in assertion equality checks.
     */
    private BigDecimal total;

    /**
     * Order lifecycle status. Typical values: {@code "pending"},
     * {@code "confirmed"}, {@code "shipped"}, {@code "delivered"},
     * {@code "cancelled"}.
     */
    private String status;

    /**
     * Row creation timestamp as returned by JDBC
     * ({@code java.sql.Timestamp} for both PostgreSQL and MySQL).
     */
    private Object createdAt;
}
