package com.omiinqa.database.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Immutable (Lombok-generated) data record representing one row from the
 * {@code products} table.
 *
 * <p><b>Design pattern — Data Transfer Object (DTO):</b>
 * {@code ProductRecord} is the read-side projection used by
 * {@link com.omiinqa.database.repositories.ProductRepository} and test
 * assertions. Containing no behaviour, it is trivially serialisable,
 * comparable, and printable — all useful qualities in assertion error messages.</p>
 *
 * <p><b>Monetary precision:</b> Price is stored as {@link BigDecimal} rather
 * than {@code double} to avoid floating-point rounding errors during
 * assertion comparisons — a common source of flaky database tests.</p>
 *
 * <p><b>Schema assumption</b> (table: {@code products}):</p>
 * <pre>
 *   id          BIGINT PRIMARY KEY
 *   name        VARCHAR
 *   category    VARCHAR
 *   price       NUMERIC(10,2)
 *   stock_qty   INT
 *   active      BOOLEAN
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductRecord {

    /** Surrogate primary key — auto-generated by the database. */
    private Long id;

    /** Human-readable product name. */
    private String name;

    /** Product category, e.g. {@code "electronics"}, {@code "clothing"}. */
    private String category;

    /**
     * Unit price; {@link BigDecimal} avoids IEEE-754 precision issues
     * that cause spurious assertion failures when comparing monetary values.
     */
    private BigDecimal price;

    /** Current inventory quantity. */
    private Integer stockQty;

    /**
     * Whether the product is visible in the catalogue.
     * Maps to a {@code BOOLEAN} / {@code TINYINT(1)} column.
     */
    private Boolean active;
}
