package com.omiinqa.database.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Immutable (Lombok-generated) data record representing one row from the
 * {@code users} table.
 *
 * <p><b>Design pattern — Data Transfer Object (DTO):</b>
 * {@code UserRecord} carries column values between the repository layer and
 * test assertions without any business logic. Keeping it a pure data holder
 * prevents test code from accidentally triggering side-effects when inspecting
 * database state.</p>
 *
 * <p><b>Lombok annotations used:</b></p>
 * <ul>
 *   <li>{@code @Data} — generates getters, setters, {@code equals}, {@code hashCode},
 *       {@code toString}.</li>
 *   <li>{@code @Builder} — enables the fluent builder pattern for readable
 *       test-data construction:
 *       {@code UserRecord.builder().id(1L).email("a@b.com").build()}.</li>
 *   <li>{@code @NoArgsConstructor} / {@code @AllArgsConstructor} — required by
 *       Lombok {@code @Builder} when combined with {@code @Data}.</li>
 * </ul>
 *
 * <p><b>Schema assumption</b> (table: {@code users}):</p>
 * <pre>
 *   id        BIGINT PRIMARY KEY
 *   name      VARCHAR
 *   email     VARCHAR UNIQUE
 *   status    VARCHAR   (e.g. "active", "inactive")
 *   created   TIMESTAMP
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserRecord {

    /** Surrogate primary key — auto-generated by the database. */
    private Long id;

    /** Full display name of the user. */
    private String name;

    /** Unique email address; used as the business key in most lookups. */
    private String email;

    /** Account status string, e.g. {@code "active"} or {@code "inactive"}. */
    private String status;

    /**
     * Row creation timestamp as returned by JDBC (vendor-specific type:
     * {@code java.sql.Timestamp} for PostgreSQL/MySQL).
     */
    private Object created;
}
